var githubresume_opt_out_users = [
    "augustl",
    "kmcallister",
    "ntlk",
    "raganwald",
    "iamdanw",
    "iamdanw_ms",
    "igalic",
    "mattfield", //"https://twitter.com/mattfieldy/status/402432266208821248"
    "evilchili",
    "jsfernandes",
    "davw",
    "listrophy",
    "jcoglan",
    "nrb",
    "drtortoise",
    "gregkare",
    "eee-c",
    "jacobian",
    "davidstanley01",
    "brianhicks",
    "jacknagel",
    "pnasrat",
    "wraithan",
    "dominic",
    "alex",
    "nikhilsrinivasan",
    "jnoller",
    "remarkablerocket",
    "bitprophet",
    "brianvh",
    "rlivsey",
    // Bigger batch until #117
    "catsby", "kennethlove", "danimal", "dreid", "lacion", "jezdez", "smoynes", "justinabrahms", 
    "fcurella", "binarydud", "dmpayton", "retro", "acdha", "pydanny", "nibrahim", "juliepagano"
];
