<!DOCTYPE html>
<html lang="en">
<head>
  <title>GitHub R&eacute;sum&eacute;</title>
  <meta charset="utf-8" />
  <!--[if IE]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.0/html5shiv.min.js"></script>
  <![endif]-->
  <meta name="keywords" content="cv, resume, hResume, github, community, free, fun, nice, useful" />
  <meta name="description" content="GitHub resumes, generated by the community, for the community." />
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/yui/2.7.0/reset-fonts-grids/reset-fonts-grids.css" media="all" />
  <link rel="stylesheet" type="text/css" href="css/resume.css" media="all" />
  <link rel="stylesheet" type="text/css" href="css/print.css" media="print" />
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="js/vendor/jquery-2.1.4.min.js"><\/script>')</script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mustache.js/0.3.0/mustache.min.js"></script>
  <script type="text/javascript" src="js/githubresume.js"></script>

  <link rel="icon" type="image/png" href="images/favicon.png">
</head>
<body id="resume">
  <noscript>You need to enable Javascript to generate and see r&eacute;sum&eacute; pages.</noscript>
</body>
</html>
